services:
  - type: web
    name: backend-syndatagen
    env: python
    buildCommand: ""
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker app.main:app
    region: oregon
    plan: free
    runtime: python
