from fastapi import APIRouter

router = APIRouter()

FAKER_FIELD_TYPES = [
    "index.no",
    "first_name",
    "last_name",
    "phone" ,
    "mobile",
    "company",
    "job",
    "salary",
    "price",
    "address",
    "street_address",
    "street_name",
    "city",
    "state",
    "country",
    "postcode",
    "zipcode",
    "uri",
    "domain",
    "domain_name",
    "ipv4",
    "date",
    "id",
    "name",
    "email",
    "uuid4",
    "url",
    "phone_number",
    "boolean",
    "random_int",
    "pyint",
    "pyfloat",
    "ipv6",
    "mac_address",
    "user_name",
    "latitude",
    "longitude",
    "time",
    "date_time",
    "date_of_birth",
    "century",
    "month",
    "year",
    "day_of_week",
    "month_name",
    "timezone",
    "bs",
    "credit_card_number",
    "credit_card_expire",
    "credit_card_provider",
    "iban",
    "file_name",
    "file_path",
    "mime_type",
    "password",
    "language_code",
    "currency_name",
    "color_name",
    "emoji",
    "yes_no",
    "age",
    "percentage",
    "invoice_number",
    "gstin",
    "text_50",
    "text_100",
    "bool",
    "gender",
    "status",
    "color",
    "hex_color",
    "country_code",
    "language"
    ]

@router.get("/faker-types/")
def get_faker_types():
    x =sorted(FAKER_FIELD_TYPES)
    return {"types": x}
